# Generated by Django 3.0.3 on 2020-03-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
