# Generated by Django 3.0.3 on 2020-03-15 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'follows',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250, null=True, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=5, null=True)),
                ('profile_image', models.CharField(max_length=100, null=True)),
                ('uuid', models.CharField(max_length=200, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('follow', models.ManyToManyField(related_name='follow_reverse', through='user.Follow', to='user.User')),
                ('grade', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Grade')),
                ('message', models.ManyToManyField(related_name='message_reverse', through='user.Message', to='user.User')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='MessageSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Message')),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='song.Song')),
            ],
            options={
                'db_table': 'message_songs',
            },
        ),
        migrations.CreateModel(
            name='MessagePlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Message')),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='song.Playlist')),
            ],
            options={
                'db_table': 'message_playlists',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_user', to='user.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='playlist',
            field=models.ManyToManyField(through='user.MessagePlaylist', to='song.Playlist'),
        ),
        migrations.AddField(
            model_name='message',
            name='song',
            field=models.ManyToManyField(through='user.MessageSong', to='song.Song'),
        ),
        migrations.AddField(
            model_name='message',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_user', to='user.User'),
        ),
        migrations.AddField(
            model_name='follow',
            name='from_follow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_follow', to='user.User'),
        ),
        migrations.AddField(
            model_name='follow',
            name='to_follow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_follow', to='user.User'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('from_follow', 'to_follow')},
        ),
    ]
