# Generated by Django 3.0.3 on 2020-03-19 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_user', to='user.User')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='MessageSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Message')),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='song.Song')),
            ],
            options={
                'db_table': 'message_songs',
            },
        ),
        migrations.CreateModel(
            name='MessagePlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Message')),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='song.Playlist')),
            ],
            options={
                'db_table': 'message_playlists',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='playlist',
            field=models.ManyToManyField(through='user.MessagePlaylist', to='song.Playlist'),
        ),
        migrations.AddField(
            model_name='message',
            name='song',
            field=models.ManyToManyField(through='user.MessageSong', to='song.Song'),
        ),
        migrations.AddField(
            model_name='message',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_user', to='user.User'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('from_follow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_follow', to='user.User')),
                ('to_follow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_follow', to='user.User')),
            ],
            options={
                'db_table': 'follows',
                'unique_together': {('from_follow', 'to_follow')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(related_name='follow_reverse', through='user.Follow', to='user.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.ManyToManyField(related_name='message_reverse', through='user.Message', to='user.User'),
        ),
    ]
