# Generated by Django 3.0.3 on 2020-03-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250, null=True, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'google_accounts',
            },
        ),
    ]
