# Generated by Django 3.0.4 on 2020-03-10 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
