# Generated by Django 3.0.3 on 2020-05-03 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200503_1127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageNumbers',
            new_name='MessageNumber',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_numbers',
            new_name='message_number',
        ),
    ]
