# Generated by Django 3.0.3 on 2020-03-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_message_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='follow',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
