# Generated by Django 3.0.3 on 2020-03-11 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200311_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
