# Generated by Django 3.0.3 on 2020-03-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
